package Cell;


/**
* Cell/Station.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Thursday, May 19, 2016 12:28:51 PM MSK
*/


/* Интерфейс базовой станции */
public interface Station extends StationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Station
